apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/roming22-org/public:63dd8dbbb5d894f84181f594f5357fc9298f61c8@sha256:be083d567a4acfd63b8916b24c4c7a888c4736ebad9d660eca41fbf9eda666da
          name: container-image
