apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/roming22-org/public:13f630791b2262e8da738187c0b911cdc6f2bb41@sha256:2693bcdcac7c7dbe49f243f9a98a7af158bd9f3f0b016d2b70b9d57dcd693e53
          name: container-image
