apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: demo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/roming22-org/demo-python:c7f9ef13702cb98e551ee9a32053fb10325027e5@sha256:f2712ee24ea26eddb4fb9d23df5bf2e2555b2e305cacc87a0918ea0b7a2d3e9f
          name: container-image
