apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: demo-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
        - image: quay.io/roming22-org/demo-python:454f277c82a89212c3feffb9327b7f3fb6390be7@sha256:4d11dbddac5845f2f41ff5cb7d8fe39ed72f22dbc21d57a19b29f9a3de3e254a
          name: container-image
