apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: demo-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
        - image: quay.io/roming22-org/public:27a82b37fa147ea85cc93515d71ce99d141aecce@sha256:956ebc4b9ff4a7861261cd935476fa4bec6ab58772e1c2e99b18856a7e54b981
          name: container-image
