apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: demo-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
        - image: quay.io/roming22-org/private:1239d0c4590cfd0a0c51bafab17358a1531a04f8@sha256:eb389cee16d41775a40140d0f79de8afaf52e9bb6ec740077d042729d46a3705
          name: container-image
